### PR TITLE
feat: allow keep not nullable fields not nullable

### PR DESCRIPTION
**Pull request by ADR-007**
Currently, `pydantic-partial` allows to set `None` for not nullable fields, which brakes the validate logic on the FastAPI endpoint.

This PR provides a new parameter `use_undefined`, to use `UNDEFINED` value as default instead of `None`, and doesn't make fields nullable.

Please take a look on the test cases.

Use case:
```python
class UserUpdateSchema(PartialModelMixin, pydantic.BaseModel):
    first_name: str
    second_name: str | None
  

@router.put()
def update_me(user: AuthUser, payload: UserUpdateSchema):
    user.set_values(payload.model_dump())

@router.patch()
def partial_update_me(user: AuthUser, payload: UserUpdateSchema.model_as_partial(
    use_undefined=True, # without this flag `first_name` can be set to `None` which is wrong
)):
    user.set_values(payload.model_dump(exclude_unset=True))

```

### CODE REVIEW

**Comment by ADR-007** [comment]
Actually, I can have everything I want to using this code snippet:
```py
T = TypeVar("T", bound=BaseModel)


def create_partial_model(
    model: type[T],
    optional_fields: Iterable[str] | None = (),
    default_value: Any = None,
) -> type[T]:
    fields = {}
    for field in optional_fields or model.model_fields.keys():
        field_info = model.model_fields[field]

        fields[field] = (
            field_info.rebuild_annotation(),
            FieldInfo.merge_field_infos(field_info, default=default_value),
        )

    return create_model(
        model.__name__ + "Partial",
        __base__=model,
        **fields,
    )
```
So, I'll, probably, just create another library.

**Comment by ADR-007** [comment]
[Here](https://github.com/ADR-007/pydantic-strict-partial/blob/main/pydantic_strict_partial/__init__.py) is the solution

**Comment by ddanier** [comment]
Not sure I like the proposed change. It just moves the issue to another value. Also I normally just use `pydantic-apply` and then apply only the set fields, so you don't need to care about fields being `None` - as those are still unset.

I will close this PR, as you created a solution in your own package ;-)

**Comment by ddanier** [comment]
Still many thanks for putting effort into this!

**Pull request closed without merging**
